### ISSUE TITLE
Got error message when change user password by IPMIUTIL command

### ISSUE THREAD

**Issue by vien20010** [arcress0/ipmiutil#14]
**Step to reproduce:**
Create new user with ipmiutil command
```
ipmiutil user set <user_id> name <username>
ipmiutil user set <user_id>  password <password>
ipmiutil user set <user_id> priv <privilege>
```
**Expected result:**
Command response success when setting account password

**Actual result: **
Command return error when setting account password
```
ipmiutil user ver 3.12
Opening lanplus connection to node 10.76.116.83 ...
GET_USERNAME: 75 73 65, status = 0, ccode=0
SETUSERNAME - 4 75 73  status = 0, ccode=0
SETUSERENAB - inputData 4 1 73, status = 0, ccode=0
SETUSERPSW - inputData 4 2 41, status = 0, ccode=0
TESTUSERPSW - inputData 4 3 41, status = 0, ccode=0
SETUSER_ACCESS - inputData 91 4 1f, status = cc ccode=cc
ipmiutil user, Invalid data field in request
```

**Comment by vien20010** [comment]
**Phenomenon:**

ipmiutil user set password fail when Set User Access command: Invalid data field in request

**Root cause:**

ipmiutil uses privilege of user configuration info which is result of GetUserInfo function 

 _ipmi_user_set function ipmiutil-3.1.8/util/iuser.c_

![image](https://user-images.githubusercontent.com/52381847/233539306-5297f094-1613-4e09-bd2b-be33429cbe51.png)

In GetUserInfo function, priv = responseData[3] of GET_USER_ACCESS command

_GetUserInfo function ipmiutil-3.1.8/util/ilan.c_

![image](https://user-images.githubusercontent.com/52381847/233539337-9ca2b3d5-d229-4c09-b7ef-7bdc9d49befc.png)


responseData[3] is 1 byte data which is defined in ipmi spec Table 22- Get User Access Command

![image](https://user-images.githubusercontent.com/52381847/233539400-50bd6511-4da8-4bfa-b849-221b926b6122.png)

ipmiutil use this byte to execute Set User Access Command. But Request Data of this command only use 4 LSB bits for privilege and 4 MSB bits is reserved (must be 0b0000). We can easily refer it in ipmi spec Table 22- Set User Access Command. 
![image](https://user-images.githubusercontent.com/52381847/233539419-e8f9199f-c901-4b20-aa90-2e0ea4b3b9b4.png)

So using a whole byte 5 (responseData[3]) of Get User Access command for request data of Set User Access Command isn’t suitable. ipmiutil should use only 4 LSB bits.

**Solution:**
Use only 4 LSB bits in GetUserInfo function
<img width="562" alt="image" src="https://user-images.githubusercontent.com/52381847/233539693-784e4b1f-e989-49a9-a831-04cd08c24ff0.png">

**Comment by arcress0** [comment]
Yes.  The change on line 1007 is the right fix in ilan.c, thank you for your detailed research.  
`upriv = responseData[3] & 0x0F;`
