### ISSUE TITLE
Fail to dump FRU bin file by IPMIUTIL command

### ISSUE THREAD

**Issue by vien20010** [arcress0/ipmiutil#15]
**Steps to reproduce:** 

Run ipmiutil command to dump FRU

`ipmiutil fru -d <fru.bin>`

**Expected result:** 

Successfully dump FRU file

**Actual result:** 

Got segmentation fault when dump FRU

**Analysis:**
frubuf is only malloc from load_fru function but ipmiutil doesn't call this function or malloc frubuf before fwrite --> segmentation fault.
![image](https://user-images.githubusercontent.com/52381847/233539892-88312ee7-75c6-4810-ab2a-308005576d93.png)

**Comment by arcress0** [comment]
Sorry.  That got broken when ifru.c changed to malloc() the fru buffer rather than being statically declared.  This needs to change to leverage pfrubuf rather than frubuf.

**Comment by arcress0** [comment]
07/05/2023 ARCress ipmiutil-3.1.9-2  changes
  lib/lanplus/lanplus.c - GH13: hpm netfn2c/cmd34 error, bridge netfn06,07/cmd34
  doc/ipmiutil.spec - GH17: do not abort if sensor command fails
  util/isensor.c - GH17: if MALFORMED, not fatal, show message before correct
08/03/2023 ARCress ipmiutil-3.1.9-3
  util/ifru.c - GH15: fails to dump FRU with -d (added load_fru for fdump)
  util/ilan.c - GH14: GH14: user set password fails w 0xCC, upriv = rd3 & 0x0F
  
See https://ipmiutil.sourceforge.net/FILES/ipmiutil-3.1.9-3.tar.gz and 
 https://ipmiutil.sourceforge.net/FILES/ipmiutil-3.1.9-3.el7.x86_64.rpm  for a version that fixes this issue.
This will be applied to github soon.

**Comment by arcress0** [comment]
The 'util/ifru.c - GH15' change was applied in ipmiutil-3.2.0 and in github 12/05/2024.
