### ISSUE TITLE
SDR record 61 is malformed, length 12 is less than minimum 12

### ISSUE THREAD

**Issue by JoergFF** [arcress0/ipmiutil#17]
Hello,

I forward this bug from Debian[1].

`Hi,

In some cases (Intel S2600STB boards), ipmiutil fails to install the 
first time:
Setting up ipmiutil (3.1.8-4) ...
SDR record 61 is malformed, length 12 is less than minimum 12
0061 GetSDR error -25, rlen = 10
dpkg: error processing package ipmiutil (--configure):
 installed ipmiutil package post-installation script subprocess 
returned error exit status 231
Processing triggers for man-db (2.11.2-2) ...
Errors were encountered while processing:
 ipmiutil
E: Sub-process /usr/bin/dpkg returned an error code (1)

The second time around, it works because 
/var/lib/ipmiutil/sensor_out.txt now exists.

The issue can be reproduced by removing /var/lib/ipmiutil/sensor_out.txt 
and running the postinst script again (with -x added here to highlight 
the problem):
# dpkg-reconfigure ipmiutil
+ sbindir=/usr/bin
+ vardir=/var/lib/ipmiutil
+ sensorout=/var/lib/ipmiutil/sensor_out.txt
+ mkdir -p /var/lib/ipmiutil
+ IPMIcmd=true
+ /usr/bin/ipmiutil sel -v
+ true
+ [ ! -f /var/lib/ipmiutil/sensor_out.txt ]
+ /usr/bin/ipmiutil sensor -q
SDR record 61 is malformed, length 12 is less than minimum 12
0061 GetSDR error -25, rlen = 10

The issue here is that "ipmiutil sel" works but "ipmi sensor" does not.
https://jff.email/cgit/ipmiutil.git/tree/debian/postinst?h=debian/3.1.9-1#n16
https://jff.email/cgit/ipmiutil.git/tree/debian/postinst?h=debian/3.1.9-1#n22

The fact that a failing "ipmiutil sensor" command prevents the 
installation is problematic. Would it please be possible to make this 
failure non-fatal?

https://bugs.launchpad.net/ubuntu/+source/ipmiutil/+bug/1786562 seems to 
be the same issue, it concerns the same error message with an Intel 
S2600STB.

PS: maybe there is also an upstream ipmiutil bug to report here? "length 
12 is less than minimum 12" sounds like an off-by-one error.

Kind regards,

Louis`

CU
Jörg

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040349

**Comment by arcress0** [comment]
Jörg,

I looked at this, and it needs a few changes:
- during postinstall, mask any errors from the sensor command
- move the error message up a few lines, before it autocorrects the minimum value. 
- do not return an overall error code for this, since the error can be auto-corrected

Thankfully this firmware issue is fairly rare.  
I have the changes coded and will submit a patch soon.  

Andy

**Comment by arcress0** [comment]
Patch submitted to this github repo (ver 3.1.9-2)

**Comment by arcress0** [comment]
Resolved in ipmiutil-3.1.9-2 in github and ipmiutil.sf.net

**Comment by arcress0** [comment]
Also included in ipmiutil-3.2.0
