### ISSUE TITLE
discover doesn't recognize asf pong from arduino

### ISSUE THREAD

**Issue by ganghuang** [arcress0/ipmiutil#4]
I am trying to make an arduino together with an ethernet shield board to enable ipmi turn a PC power on/off etc.

I can use the ipmiutil discover to send out ASF ping and my board does return ASF pong as the wireshark captured below. 

But the ipmituil does not recognize the pong as a response, so still report back 0 response. 

![image](https://user-images.githubusercontent.com/7526459/155091375-9264d1ad-23f7-43eb-97ac-321367b80fdd.png)

![image](https://user-images.githubusercontent.com/7526459/155091443-523f843a-1207-4cc8-b0ba-5aebc1e87481.png)

I even copied the mac address of a supermicro board over but the ipmiutil still says 0 responses. 
What else does the discover waiting for?

**Comment by ganghuang** [comment]
@Andy Thank you for the reply, please see below:
1. Results of ipmiutil discover with a range (will probably work), example: # ipmiutil discover -b 192.168.1.50 -e 192.168.1.250 
This runs much slower as it seems ping each ip in sequence. 
But at the end, it does got the result.
![image](https://user-images.githubusercontent.com/7526459/155204285-1b0a6607-8ce7-4eab-93ac-f9a7b2377283.png)


2. traceroute from 192.168.1.103 to 192.168.1.244 (verify that they are on the same subnet, probably so) 
Seems it just go there directly
![image](https://user-images.githubusercontent.com/7526459/155202688-f2e454fb-cad9-4282-9a14-d9be4bd8322e.png)

3. Output of 'ipmiutil lan' run on the Arduino system. (perhaps the netmask is wrong?) 
The arduino system does not have a OS, so I can not run ipmiutil on that system. 
But I can check the netmask for the arduino network shield and it give me 255.255.255.0

**Comment by ganghuang** [comment]
Another test with root:
 ipmiutil discover -a -m -x > /tmp/t1
I got the t1 attached. I don't know why there are so many responses on my network, but the pong response does recognized at line 42. 
![image](https://user-images.githubusercontent.com/7526459/155207243-c9113612-feb0-40c5-b244-b882154a1334.png)


And if I do ipmiutil discover -m, I can get the response, but if I don't do the -m, there is 0 response
![image](https://user-images.githubusercontent.com/7526459/155207558-0f1614d2-dc40-4c6d-82f3-903df2154f04.png)

**Comment by arcress0** [comment]
This is an issue specific to the arduino platform, and using idiscover -m (raw mode) does get a response.  The fact that arduino does not respond to normal broadcast pings seems to be an error with the platform, not ipmiutil.
