### ISSUE TITLE
isensor -i flag; can it be updated to support a list of sensor IDs?

### ISSUE THREAD

**Issue by btowntkd** [arcress0/ipmiutil#5]
Currently, isensor supports the `-i` flag for specifying a single, specific sensor ID (`-i 0xff`) or a range of sensor IDs (`-i 0x01-0xff` or `-i 0x01,0xff`).

Can we update this functionality? It seems like the comma separator would be more intuitively used as a comma-separated list of sensor ID (i.e. `-i 0x01,0x02,0xAA,0xBB,0xFF`).  There is currently no option to specify a list of sensor IDs, which seems like a valid and likely use-case.

**Comment by arcress** [comment]
I see what you mean.  That would mean a change to the get_idx_range() subroutine to loop on the comma delimiter, but shouldn't be too much work.  I don't have a time slice to do that right now, but could do that shortly.   Or you could submit a patch if you like.

**Comment by arcress0** [comment]
I didn't have bandwidth to implement and test doing a list as well as a range in get_idx_range() in time for ipmiutil-3.1.9.

**Comment by arcress0** [comment]
In ipmiutil-3.1.9 there is a fix to isensor.c (get_idx_range) to show the last idx in range.  Hopefully that is sufficient for the time being.
