### ISSUE TITLE
isensor -i flag with range of IDs: the last sensor ID in the range is not included

### ISSUE THREAD

**Issue by btowntkd** [arcress0/ipmiutil#6]
This is a potential off-by-one error; when using the isensor `-i` flag with a range of sensor IDs (i.e. `-i 0x01-0xff`), the last sensor ID is not included in the report (`0xFE` is included, `0xFF` is not).

Is this intended behavior?  If so, the documentation should reflect this, as it is not intuitive. If not, we should update the loop so that the last sensor ID is included in the range.

**Comment by arcress0** [comment]
fixed in ipmiutil-3.1.9
