### ISSUE TITLE
Telegraf input data formats - sensor output formats

### ISSUE THREAD

**Issue by VegethB** [arcress0/ipmiutil#8]
As the title suggests, I don't understand what data output format is what you get from the "sensor" parameter either using the -c option or not.

![Immagine 2022-10-26 184825](https://user-images.githubusercontent.com/17975351/198088568-fc676c44-74ab-4fca-9398-fc73243337a6.png)

The goal would be to record the values of the fans, power supply and current sensors (including sensor names).
Now, the command is the one in the screen, the problem is that I have no idea what kind of output it is.
So I ask 1 thing:
If it is a custom output, you can implement a command to have one of these listed data outputs:

https://docs.influxdata.com/telegraf/v1.24/data_formats/input/
or
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

Thanks in advance

**Comment by arcress0** [comment]
The sensor -c  output is a CSV format, but the delimiter is '|' instead of ',' because some of the fields do contain commas.
